### ISSUE TITLE
Feature Request: Support for event_id and deduplication

### ISSUE THREAD

**Issue by mabajian** [firmnardians/react-tiktok-pixel#1]
Hi @firmnardians ,

Thank you for creating this library, it's really helped me with implementing the pixel in React. However, I notice you did not yet have support for adding `event_id`, so I opened this feature request.

Could you please add support for new `event_id` object that can be passed into tracking call? 
[TikTok Documentation for Deduplication
](https://ads.tiktok.com/marketing_api/docs?id=1723170195197953)
For example:
```
ttq.track('AddToCart', {
    content_id: '301',
    content_type: 'product',
    content_name: 'dress',
    quantity: 1,
    price: 8,
    value: 9.2,
    currency: 'USD',
},
{event_id:'1239485'});
```
where `{event_id:'1239485'}` is an additional object that can be passed to the tracking call.

Thanks in advance 🙏

**Comment by firmnardians** [comment]
Hi @mabajian

Are you still using this package?

**Comment by mabajian** [comment]
hi, @firmnardians 
Yes still using it, but no longer blocked by this. I was able to workaround by calling the tiktok function `ttq` directly, after initializing it with your `config()` method.

**Comment by firmnardians** [comment]
> hi, @firmnardians Yes still using it, but no longer blocked by this. I was able to workaround by calling the tiktok function `ttq` directly, after initializing it with your `config()` method.

Ok, I will close this issue. 

Thank you.
